### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by Thomas-Gallant** [Sudokuru/Frontend#318]
Acceptance criteria: about us page is added

- Everyone who has contributed to the project is credited
- Link to github / youtube 
- Core values

**Comment by Gregory711** [comment]
Plan of what to include:
- [Values from ReadMe](https://github.com/Sudokuru/Frontend?tab=readme-ov-file#sudokuru-is-an-open-source-project-focused-on-developing-a-world-class-cross-platform-sudoku-app-we-aim-to-provide-a-delightful-user-experience-while-also-contributing-to-the-community-by-building-a-collection-of-reusable-software-modules-these-modules-are-designed-to-be-free-well-documented-modern-and-interoperable-allowing-developers-to-easily-incorporate-them-into-their-own-sudoku-related-projects)
- Link to Github (fancy with Github logo)
- Link to Youtube (fancy with Youtube logo)
- Blurb about started by computer science students at UCF originally as senior design project and continued as OSS project by members of the original team. Links to all contributors Githubs separated into active and inactive contributors.
